package antBrain;

import engine.DummyEngine;

/**
 * Used by the DummyEngine to get Brain objects from file, or generated by the GeneticAlgorithm
 * 
 * @author pkew20 / 57116
 * @version 1.0
 */
public class BrainController {
	public static Brain readBrainFrom(String path) {
		return BrainParser.readBrainFrom(path);
	}
	
	public static Brain getBestGABrain(Brain exampleBrain, DummyEngine dummyEngine,
		int epochs, int rounds, int popSize, int elite, int mutationRate) {
		GeneticAlgorithm geneticAlgorithm = new GeneticAlgorithm();
		geneticAlgorithm.createPopulation(exampleBrain, popSize);
		geneticAlgorithm.evolve(dummyEngine, epochs, rounds, elite, mutationRate);
		return geneticAlgorithm.getBestBrain();
	}
}
