package engine;

/**
 * Class to hold scores generated by the run of a simulation.
 * 
 * @author wjs25
 */
public class GameStats {
	//The self explanatory stats it holds
	private int winner; // 0 is black brain, 1 is red
	private int foodInBlackAnthill;
	private int foodInRedAnthill;
	private int blackAntsSurviving;
	private int redAntsSurviving;
	
	/**
	 * 
	 * 
	 * @param winner The brain which won the game.
	 * @param foodInBlackAnthill The amount of food left in the black anthill at
	 * 							 the end of the game.
	 * @param foodInRedAnthill The amount of food left in the red anthill at
	 * 						   the end of the game.
	 * @param blackAntsSurviving Number of black ants left surviving at the end
	 * 							 of the game.
	 * @param redAntsSurvivig Number of black ants left surviving at the end
	 * 						  of the game.
	 */
	public GameStats(int winner, int foodInBlackAnthill, 
					 int foodInRedAnthill, int blackAntsSurviving,
					 int redAntsSurviving) {
		this.winner = winner;
		this.foodInBlackAnthill = foodInBlackAnthill;
		this.foodInRedAnthill = foodInRedAnthill;
		this.blackAntsSurviving = blackAntsSurviving;
		this.redAntsSurviving = redAntsSurviving;
	}
	
	/**
	 * @return The winner
	 */
	public int getWinner() {
		return this.winner;
	}
	
	/**
	 * @return Amount of food in black anthill
	 */
	public int getFoodInBlackAnthil() {
		return this.foodInBlackAnthill;
	}
	
	/**
	 * @return Amount of food in black anthill
	 */
	public int getFoodInRedAnthill() {
		return this.foodInRedAnthill;
	}
	
	/**
	 * @return Amount of black ant survivors
	 */
	public int getBlackAntsSurviving() {
		return this.blackAntsSurviving;
	}
	
	/**
	 * @return Amount of red ant survivors
	 */
	public int getRedAntsSurvivig() {
		return this.redAntsSurviving;
	}
}
