package engine;

/**
 * @title Random
 * @purpose to generate pseudorandom numbers between 0 (inclusive) and the value
 * given (exclusive)
 * 
 * @author pkew20 / 57116
 * @version 1.0
 */
public class Random {
	private static final long serialVersionUID = 1L;
	private int s;
	
	/**
	 * @title Random
	 * @purpose to construct objects of type Random
	 * @param seed a value that affects the sequence of numbers generated by this
	 * Random, the same seed will produce the same set of numbers
	 */
	public Random(int seed) {
		if(seed == 0){
			this.s = (int) (Math.random() * Integer.MAX_VALUE + 1);
		}else{
			this.s = seed;
		}
		
		for(int i = 0; i < 3; i++){
			nextS();
		}
	}
	
	private int nextS() {
		return this.s = this.s * 22695477 + 1;
	}
	
	private int nextX() {
		return mod((nextS() / 65536), 16384);
	}
	
	private static int mod(int x, int y) {
		int r = x % y;
	    if(r < 0){
	        return r + y - 1;
	    }
	    return r;
	}
	
	/**
	 * @title randomInt
	 * @purpose to get the next int in the sequence given by the seed
	 * @param n the range of the value returned is from 0 (inclusive) to
	 * n (exclusive)
	 * @return a pseudorandom int between 0 and n
	 */
	public int randomInt(int n) {
		return mod(nextX(), n);
	}
}
